app {
  http {
    host = "0.0.0.0"
    port = 8081
    timeout = 40 seconds
  }
  one-frame {
    base-uri = "http://[0:0:0:0:0:0:0:0]:8080",
    token = "10dc303535874aeccc86a8251e6992f5"
  },
  cache-rates {
    ttl = 180 seconds
    retry-delay = 50 millis
    max-retries = 20
    max-rate-age = 300 seconds
  }
}

